on:
  workflow_call:
    inputs:
      run-name:
        required: false
        description: 'Analisa Imagen y Crea Contenedor'
        default: 'Running Build And Analize Docker Image'
        type: string        
name: clonacionRepositorio
run-name: ${{inputs.run-name}}
jobs:
  Clon:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repositorio
        uses: MoeKernel/github-repo-action@v3.1
        with:
          branch: 'X'
          owner: 'Repcz'
          repository: 'tool'
      - name: Acceso al conteniso del repositorio
        run: |
          #Se dejan lineas para subir contenido clonado a repositorio
          #pero dado que requeriran de usuario y password se dejan comentadas
          #sin embargo, en base a lo expuesto en clases se entiende que el comando - uses: actions/checkout@v4 tambien realiza un clonado que es utilizable. 
          #cd rules
          #git init
          #git add .
          #git commit -m "Add existing project files to Git"
          #git remote add origin
          #git push -u -f origin main
          #cd ..
          #rm -rf rules
