name: Clone and Commit

on: [push]

permissions:
  contents: write  # 确保对仓库内容有写权限
  workflows: write
  
jobs:
  clone-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2
      
    - name: Clone Public Repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2.1
      with:
        depth: 1
        branch: 'X'  # 替换为实际分支名
        owner: 'Repcz'  # 替换为实际拥有者
        repository: 'Tool'  # 替换为实际仓库名

    - name: Remove .git folder from cloned repository
      run: rm -rf Tool/.git

    - name: Copy files
      run: |
        cp -r Tool/* .
        cp -r Tool/.[!.]* .

    - name: Configure git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add .
        git commit -m "Add files from public repository"
        git push https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }}@github.com/fxcl/rules.git HEAD:main
