name: Clone and Commit

on: [push]

jobs:
  clone-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2
      
    - name: Clone Public Repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2.1
      with:
        depth: 1
        branch: 'X'
        owner: 'Repcz'
        repository: 'Tool'

    - name: Remove .git folder from cloned repository
      run: rm -rf Tool/.git

    - name: Copy files
      run: |
        cp -r Tool/* .
        cp -r Tool/.[!.]* .

    - name: Configure git
      run: |
        git config --global user.name 'fxcl'
        git config --global user.email 'me@gnux.cn'

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Add files from public repository"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
