name: Clone and Commit

on: [push]

jobs:
  clone-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2
    - name: Clonar Repositorio
      uses: GuillaumeFalourd/clone-github-repo-action@v2.1
      with:
          depth: 1
          branch: 'X'
          owner: 'Repcz'
          repository: 'tool'
    - name: Copy files
      run: |
        cp -r tool/* .
        cp -r tool/.[!.]* .

    - name: Configure git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Add files from public repository"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
